config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :authors do 
    resources :articles
  end
  # resources :authors do
  resources :articles do 
    resources :comments
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

    include Visible

    belongs_to :author, optional: true
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/author.rb
class Author < ApplicationRecord

    # include Visible
    has_many :articles, dependent: :destroy
    
    VALID_NAME_REGEX = /\A[^0-9!@#\$%\^&*+_=]+\z/

    validates :fname, :lname, presence: true, 
              format: { with: VALID_NAME_REGEX, message: "only allows letters and '-' symbol" }
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/models/comment.rb
class Comment < ApplicationRecord
include Visible

  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
          where(status: 'public').count
        end
      end
  
    def archived?
      status == 'archived'
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show] 
  
  def index
    @articles = Article.all
    

  end
  def show
    @article = Article.find(params[:id])

  end
  def new
    @article = Article.new
    @authors = Author.all
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
    @authors = Author.all
    @authors = nil if @article.author_id.nil?
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body, :author_id, :status)
    end


end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
   
  def index
    @authors = Author.all;
  end
  def show
    @author = Author.find(params[:id]); 
    
  end
  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to @author, status: :see_other
  end
  

  private
    def author_params
      params.require(:author).permit(:fname, :lname, :email, :status)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end

      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>


  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :author_id, "Author" %><br>
  <% if @authors && !@authors.empty? %>
    <%= form.collection_select :author_id, @authors, :id, :fname, { prompt: "Select author" } %>
  <% else %>
    <%= form.select :author_id, Author.pluck(:fname, :id), { prompt: "Select author else" } %>
  <% end %>
</div>


  <div>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
</div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
        <% if article.author %>
        <span> <%= link_to article.author.fname + " " + article.author.lname, article.author %></span>
        <% else %>
          <span> Author unknown</span>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %> <br>
<%= link_to "All authors", authors_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/authors/_form.html.erb
<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :First_name %><br>
    <%= form.text_field :fname %>
    <% @author.errors.full_messages_for(:fname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Last_name %><br>
    <%= form.text_field :lname %>
    <% @author.errors.full_messages_for(:lname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Email %><br>
    <%= form.text_field :email %>
    <% @author.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
    <% @authors.each do |author|%>
     
    <li>
        <a href="<%= author_path(author)%>">
        <%= author.fname %>
        <%= author.lname %>
        </a>
    </li>
    
     <% end %>
</ul>

<%= link_to "New Author", new_author_path %><br>
<%= link_to "All articles", articles_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render "form", author: @author %>

app/views/authors/show.html.erb
<h1><%= @author.fname %> <%= @author.lname %></h1>
<p><%= @author.email %></p>

<ul>
     <li><%= link_to "Edit", edit_author_path(@author) %></li>

<li><%= link_to "Destroy", author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Articles:</h2>
<ul>
  <% @author.articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>